baseURL = "https://example.com"
languageCode = "en-us"
title = "deadalleys."
theme = "modern-portfolio"

[params]
description = "Everything is eventual."
author = "deadalley"
github = "https://github.com/deadalley"

[menu]

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Development"
url = "/development/"
weight = 2

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 3

[[menu.main]]
name = "Photography"
url = "/photography/"
weight = 4

[markup]

[markup.goldmark]

[markup.goldmark.renderer]
unsafe = true
