baseURL = "https://example.com"
languageCode = "en-us"
title = "deadalleys."
theme = "modern-portfolio"

[params]
description = "Everything is eventual."
author = "deadalley"
github = "https://github.com/deadalley"

[menu]

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Development"
url = "/development/"
weight = 2

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 3

[[menu.main]]
name = "Photography"
url = "/photography/"
weight = 4

[[menu.main]]
name = "Art"
url = "/art/"
weight = 5

[markup]

[markup.goldmark]

[markup.goldmark.renderer]
unsafe = true

[security]

[security.funcs]
getenv = ["^IMAGEKIT_API_KEY$"]

[caches]

[caches.images]
dir = ':cacheDir/images'
