name = "Modern Portfolio"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = "A modern, responsive portfolio theme for Hugo"
homepage = "http://example.com/"
tags = ["portfolio", "responsive", "modern", "photography", "blog"]
features = ["responsive", "photography", "video", "blog"]
min_version = "0.41.0"

[author]
name = "DeadAlley"
homepage = "http://example.com/"
